export const ANIMATION_MAX_DIMENSION = 75
export const ANIMATION_TOTAL_SHAPES = 100
export const ANIMATION_RESIZE_SPEED = 0.6
export const ANIMATION_OPACITY_SPEED = 0.01
export const ANIMATION_REPOSITION_SPEED = 0.3
export const COLOR_DARK_BLUE_RGBA = [32, 47, 60, 0]
export const COLOR_GREY_RGBA = [73, 85, 94, 0]
export const COLOR_WHITE_RGBA = [255, 255, 255, 0]
export const URL_GITHUB = 'https://github.com/nath-codes'
export const URL_INSTAGRAM = 'https://www.instagram.com/nathan.kansu'
